### ISSUE TITLE
Join API SIG?

### ISSUE THREAD

**Issue by philliphoff** [dapr/sig-api#2]
As a tool-er and (very) occasional contributor to Dapr, I'd like to be in the API SIG.

**Comment by seeflood** [comment]
Cool , welcome every one :)
I haven't participated in a SIG before and don't know we should next, could u give some advice?
I plan to write an initial proposal first

**Comment by yaron2** [comment]
@seeflood a proposal is a good way to start!

**Comment by yaron2** [comment]
@seeflood pinged you on Discord.

**Comment by salaboy** [comment]
I am closing this issue as I will be creating new issues to organise the working group, including re opining the discord channel but also some information about how to join the group and issues for people to work on.
